version: '3.9'
services:
  server: 
    build: ./server
    ports:
      - 3000:3000
    environment:
      - PORT=3000

  client:
    build: ./client
    depends_on:
      - server
    ports:
      - 8080:80
      - 4200:4200